# Generated by Django 5.2.4 on 2025-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
